name: Build photo manifest
permissions:
  contents: write

on:
  push:
    paths:
      - 'img/*-640.jpg'
      - 'img/*-1280.jpg'
      - 'img/*-2560.jpg'
      - '.github/workflows/build-manifest.yml'

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build img/photos.json from /img
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p img
          # collect unique basenames that have all 3 sizes
          mapfile -t BASENAMES < <(ls img/*-640.jpg 2>/dev/null | sed 's@.*/@@;s@-640\.jpg$@@' | sort -u)
          echo "[" > img/photos.json
          first=1
          for b in "${BASENAMES[@]}"; do
            if [[ -f "img/${b}-1280.jpg" && -f "img/${b}-2560.jpg" ]]; then
              # comma between objects
              if [[ $first -eq 0 ]]; then echo "," >> img/photos.json; fi
              first=0
              # crude, but safe defaults; customize later by hand if needed
              TITLE="${b}"
              OVERLAY="${b}"
              ALT="${b}"
              printf '  {"base":"%s","title":"%s","overlay":"%s","alt":"%s"}' "$b" "$TITLE" "$OVERLAY" "$ALT" >> img/photos.json
            fi
          done
          echo "" >> img/photos.json
          echo "]" >> img/photos.json

      - name: Commit manifest
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add img/photos.json
          git commit -m "Update photo manifest" || echo "No changes"
          git push
