name: Build photos (resize + manifest)

permissions:
  contents: write

on:
  push:
    paths:
      - 'img/originals/*.jpg'
      - 'img/originals/*.jpeg'
      - 'img/originals/*.JPG'
      - 'img/originals/*.JPEG'
      - '.github/workflows/build-manifest.yml'
  workflow_dispatch:

concurrency:
  group: build-photos
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Ensure ImageMagick is available
        run: convert -version

      - name: Resize originals into 640/1280/2560
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob nocaseglob
          mkdir -p img img/originals
          
          for f in img/originals/*.{jpg,jpeg,JPG,JPEG}; do
            [ -e "$f" ] || continue
            stem="$(basename "${f%.*}")"
            for size in 640 1280 2560; do
              out="img/${stem}-${size}.jpg"
              if [[ ! -f "$out" ]]; then
                convert "$f" -auto-orient -strip -resize "${size}x${size}>" -quality 88 "$out"
                echo "Wrote $out"
              fi
            done
          done

      - name: Build img/photos.json from resized images
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t BASENAMES < <(ls img/*-640.jpg 2>/dev/null | sed 's@.*/@@;s@-640\.jpg$@@' | sort -u)
          echo "[" > img/photos.json
          first=1
          for b in "${BASENAMES[@]}"; do
            if [[ -f "img/${b}-1280.jpg" && -f "img/${b}-2560.jpg" ]]; then
              if [[ $first -eq 0 ]]; then echo "," >> img/photos.json; fi
              first=0
              printf '  {"base":"%s","title":"%s","overlay":"%s","alt":"%s"}' "$b" "$b" "$b" "$b" >> img/photos.json
            fi
          done
          echo "" >> img/photos.json
          echo "]" >> img/photos.json

      - name: Commit and push generated files safely
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "actions-bot"
          git config user.email "actions@users.noreply.github.com"

          # Sync with remote even if the working tree has generated files
          git pull --rebase --autostash

          git add img/*.jpg img/photos.json 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Resize photos + update manifest"

          # Try push; if rejected, rebase with autostash and retry once
          if ! git push; then
            git pull --rebase --autostash
            git push
          fi
      
